allowBuilds:
  esbuild: true
  workerd: true
minimumReleaseAgeExclude:
  - '@cloudflare/workers-types@5.20260921.1'
  - '@effect/platform-bun@4.0.0-rc.117'
  - '@effect/platform-node-shared@4.0.0-rc.117'
  - '@effect/platform-node@4.0.0-rc.117'
  - effect@4.0.0-rc.117
